version: "3.8"
services:
  db:
    container_name: db
    ports:
      - "5432:5432"
    build:
      dockerfile: "./docker/Dockerfile.db"
    restart: unless-stopped
    environment:
      - POSTGRES_USER
      - POSTGRES_PASSWORD
      - POSTGRES_DB
    volumes:
      - db-data:/var/lib/postgresql/data

  testdb:
    container_name: testdb
    ports:
      - "5433:5433"
    build:
      dockerfile: "./docker/Dockerfile.test.db"
    restart: unless-stopped
    environment:
      - POSTGRES_USER
      - POSTGRES_PASSWORD
      - POSTGRES_DB
    volumes:
      - testdb-data:/var/lib/postgresql/data

volumes:
  db-data:
  testdb-data:
